<?php

/* * *DMS* * */
$ATTRIBUTE_NAME['audit']['dms_wf_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from dms_workflow_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['dms_master_related_to_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from dms_master_related_to_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['dms_master_sub_related_to_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from dms_master_sub_related_to_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['dms_master_target_date_expiry_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from dms_master_target_date_expiry_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['dms_master_exam_pass_mark_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from dms_master_exam_pass_mark_audit_trail_view	 where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['dms_master_exam_attempt_limit_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from dms_master_exam_attempt_limit_audit_trail_view	 where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['dms_master_monitoring_limit_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from dms_master_monitoring_limit_audit_trail_view  where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
/* * *CCM* * */
$ATTRIBUTE_NAME['audit']['ccm_wf_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ccm_wf_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['ccm_master_change_type_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ccm_master_change_type_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['ccm_master_related_to_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ccm_master_related_to_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['ccm_master_sub_related_to_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ccm_master_sub_related_to_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['ccm_master_affect_doc_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ccm_master_affect_doc_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['ccm_master_exam_pass_mark_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ccm_master_exam_pass_mark_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['ccm_master_exam_attempt_limit_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ccm_master_exam_attempt_limit_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['ccm_master_monitoring_limit_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ccm_master_monitoring_limit_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
/* * *CAPA* * */
$ATTRIBUTE_NAME['audit']['capa_wf_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from capa_workflow_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['capa_master_exam_pass_mark_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from capa_master_exam_pass_mark_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['capa_master_exam_attempt_limit_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from capa_master_exam_attempt_limit_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['capa_target_date_expiry_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from capa_target_date_expiry_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
/* * *VMS* * */
$ATTRIBUTE_NAME['audit']['vms_wf_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_wf_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['vms_master_add_vendor_plant'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_master_add_vendor_plant_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['vms_master_add_vendor_org'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_master_add_vendor_org_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['vms_master_vendor_type_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_master_vendor_type_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['vms_master_vendor_agenda_category_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_master_vendor_agenda_category_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['vms_master_vendor_agenda_sub_category_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_master_vendor_agenda_sub_category_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['vms_master_vendor_score_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_master_vendor_score_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['vms_master_vendor_validity_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_master_vendor_validity_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['vms_master_reminder_mail_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from vms_master_reminder_mail_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
/* * *AMS* * */
$ATTRIBUTE_NAME['audit']['ams_wf_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ams_wf_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['ams_master_sub_type_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from ams_master_sub_type_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
/* * *QMS Master* * */
$ATTRIBUTE_NAME['audit']['qms_product_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_product_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_material_type_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_material_type_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_material_sub_type_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_material_sub_type_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_instrument_equipment_type_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_instrument_equipment_type_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_instrument_equipment_details_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_instrument_equipment_details_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_customer_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_customer_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_market_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_market_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_process_stage_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_process_stage_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_classification_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_classification_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['qms_measurement_master_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from qms_measurement_master_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
/* * *OOS Master* * */
$ATTRIBUTE_NAME['audit']['oos_master_checklist_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from oos_master_checklist_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['oos_master_test_details_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from oos_master_test_details_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
$ATTRIBUTE_NAME['audit']['oos_wf_audit_trail'] = 'select user_name,ip_address,created_date,action,new_value,old_value,status from oos_wf_audit_trail_view where ref_object_id like \'$arg[0]\' and year like \'$arg[1]\' and month like \'$arg[2]\' and  plant like \'$arg[3]\' and  dept like \'$arg[4]\' and user_id like \'$arg[5]\' and created_date > \'$arg[6]\' and created_date < \'$arg[7]\'';
/* * *DASHBOARD Analytics* * */
