<?php

define("_URL_", (!empty($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . ((!empty($_SERVER['SERVER_PORT'])
        and $_SERVER['SERVER_PORT'] != 80) ? ':' . $_SERVER['SERVER_PORT'] : '')
        . substr($_SERVER['PHP_SELF'], 0, strrpos($_SERVER['PHP_SELF'], '/') + 1));
// set debug = 1 to help analyse errors
$DEBUG = 0;
/**
 * This is the user that file directories and uploaded files
 * will be owned by.
 */
if (!defined("_WEBUSR_"))
    define("_WEBUSR_", "apache");

/**
 * This is the group that file directories and uploaded files
 * will be owned by.
 */
if (!defined("_WEBGRP_"))
    define("_WEBGRP_", "apache");

/**
 * Location of the includes directory.  Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_INCLUDES_"))
    define("_INCLUDES_", _PATH_ . "/includes/");


/**
 * Location of the classes directory. Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_CLASSES_"))
    define("_CLASSES_", _INCLUDES_ . "classes/");

/**
 * Location of the DB classes directory.These class files are generated by DB_Dataobject Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_DB_CLASSES_"))
    define("_DB_CLASSES_", _INCLUDES_ . "db_classes/");


/**
 * Location of the DB ini File.This file is generated by            
 * DB_Dataobject Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  
 */
if (!defined("_DB_INI_"))
    define("_DB_INI_", _PATH_ . "/db/db_lm_dataobject.ini");


/**
 * Location of the resources directory. Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_RESOURCES_"))
    define("_RESOURCES_", _INCLUDES_ . "resources/");


/**
 * Location of the errors directory. Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_ERRORS_"))
    define("_ERRORS_", _INCLUDES_ . "errors/");

/**
 * Location of the error definition  file. Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  
 */
if (!defined("_ERROR_FILE_"))
    define("_ERROR_FILE_", _INCLUDES_ . "errors/lm.errors");

/**
 * Location of the modules directory. Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_MODULES_"))
    define("_MODULES_", _PATH_ . "/lib/");

/**
 * Location of the functions directory. Unless you have modified the
 * original directory structure of Logicmind  you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_FUNCTIONS_"))
    define("_FUNCTIONS_", _INCLUDES_ . "functions/");

/**
 * Location of the db files directory. Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_DB_"))
    define("_DB_", _PATH_ . "/db/");


/**
 * Location of the logs directory. Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_LOGS_"))
    define("_LOGS_", _PATH_ . "/logs/");

/**
 * Location where uploaded files will be kept.  This directory must
 * be writable by your webserver, but for security purposes should
 * not be web accessible.  Make sure to include the trailing slash.
 */
if (!defined("_FILES_"))
    define("_FILES_", _PATH_ . "/files/");


/**
 * Location where images will be kept.  Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_IMAGES_"))
    define("_IMAGES_", _URL_ . "/images/");

/**
 * Location where css will be kept.  Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_CSS_"))
    define("_CSS_", _PATH_ . "/styles/");

/**
 * Setup Mail sending Method
 * 
 */
if (!defined("_LM_MAIL_SENDING_METHOD_"))
define("_LM_MAIL_SENDING_METHOD_", "mail");
  //  define("_LM_MAIL_SENDING_METHOD_", "smtp");

/**
 * Location where scripts will be kept.  Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_SCRIPTS_"))
    define("_SCRIPTS_", _PATH_ . "/scripts/");

/**
 * Location where file attachments related to PART module will be kept.  Unless you have modified the
 * original directory structure of Logicmind you should not have
 * to change this.  Make sure to include the trailing slash.
 */
if (!defined("_SOP_TMP_VAULT_"))
    define("_SOP_TMP_VAULT_", _PATH_ . "/data_vault/tmp_sop/");
if (!defined("_TMP_VAULT_"))
    define("_TMP_VAULT_", _PATH_ . "/data_vault/tmp/");


if (!defined("_PROFILE_VAULT_"))
    define("_PROFILE_VAULT_", _PATH_ . "/data_vault/profile/");

if (!defined("IMAGE_MEDIUM_DIR"))
    define("IMAGE_MEDIUM_DIR", "./data_vault/profile/uploades/medium/");

if (!defined("IMAGE_SMALL_DIR"))
    define("IMAGE_SMALL_DIR", "./data_vault/profile/uploades/small/");

if (!defined("DEFAULT_USER_IMAGE"))
    define("DEFAULT_USER_IMAGE", "./img/default.jpg");

if (!defined("_UPLOAD_MAX_FILE_SIZE_"))
    define("_UPLOAD_MAX_FILE_SIZE_", ini_get('upload_max_filesize') . "B");

if (!defined("_DOC_VAULT_"))
    define("_DOC_VAULT_", _PATH_ . "/data_vault/doc_vault/");

if (!defined("_PART_TMP_"))
    define("_PART_TMP_", "lib/part/tmp/");


/**
 * Smarty Constants
 */
if (!defined("SMARTY_DIR"))
    define("SMARTY_DIR", "Smarty/libs/");
if (!defined("_TEMPLATES_"))
    define("_TEMPLATES_", _PATH_ . "/templates/");

// Addded this fpdf font path as it is required for the PDF Generation
//if(!defined("FPDF_FONTPATH"))
//define("FPDF_FONTPATH",_PATH_."/includes/fpdf/font/");
?>
